### ISSUE TITLE
[iOS] white path trailing card drag

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#35]
@pixelzoom, I believe I've narrowed this issue down to model and iOS. I've tested on our 5 iPads and decided this is an issue only on Witten and Tycho (iPad **2**, iOS **9.3.1**).

From sim start up, dragging a card through the function machine has a chance to leave a white path behind, around the edges of the function machine. This is regardless of screen, card, direction, and function presence. It only seems that drag speed is a factor, I see this more while dragging slowly:

https://drive.google.com/file/d/0B3HJopSo_QqLWFFjdDJ0NlRJVEU/view?usp=sharing

For phetsims/tasks/issues/589.

**Comment by pixelzoom** [comment]
Looks like it could be related to clipArea, undoubtedly a scenery issue, but no idea how to address this. This is a showstopper.

Assigning to @ariel-phet to prioritize and assign.

Mentioning @jonathanolson since he will undoubtedly be involved.

**Comment by pixelzoom** [comment]
I reproduced this on my iPad2 with iOS 9.3.1 and mobile Safari. It occurs only if you drag slowly, and the output carousel is empty. As soon as there's a card in the output carousel, the problem mysteriously disappears.

**Comment by pixelzoom** [comment]
This problem appears to be specific to iOS 9.3.1 on iPad2. Newer models (iPad3) with iOS 9.3.1 did not exhibit the problem. Other iPad2s running iOS 8.4.1 did not exhibit the problem.

[5/11/16, 12:42:24 PM] Chris Malley: And idea why this is an issue "only on Witten and Tycho"?  Are the other iPads on some older iOS version?
[5/11/16, 12:43:20 PM] Steele Dalton: yes
[5/11/16, 12:43:35 PM] Steele Dalton: we have different combos of models and iOSes
[5/11/16, 12:43:43 PM] Chris Malley: is there a document somewhere that describes the test hardware?
[5/11/16, 12:43:55 PM] Steele Dalton: PhET Asset Inventory
[5/11/16, 12:44:50 PM] Chris Malley: That doc appears to be out of date. It indicates that Witten and Tycho are 9.3, not 9.3.1
[5/11/16, 12:45:08 PM] Chris Malley: did you test on diSessa?
[5/11/16, 12:45:42 PM] Steele Dalton: yes I did
[5/11/16, 12:45:55 PM] Chris Malley: and no problem there? is it running 9.3?
[5/11/16, 12:46:09 PM] Steele Dalton: 9.3.1 actually, and no problem
[5/11/16, 12:46:59 PM] Chris Malley: So Lave (iPad2) with iOS 8.4.1 was no problem either?
[5/11/16, 12:47:04 PM] Steele Dalton: correct
[5/11/16, 12:47:24 PM] Chris Malley: so it appears to be iOS 9 related, and only on iPad2.
[5/11/16, 12:47:40 PM] Steele Dalton: so that leaves us with saying it's how the iPad 2 hardware s handling the iOS

**Comment by ariel-phet** [comment]
Took a look at this bug.

This is important. It should be addressed, it should be top priority, but I am not going to go so far as to call it a "showstopper"

**Comment by pixelzoom** [comment]
Perhaps you have a different definition of "showstopper".  Would you release the sim with this issue and consider it usable on iOS?  Imo, it involves such a fundamental user interact and is so distracting that it gets in the way of using the sim.

**Comment by ariel-phet** [comment]
Well...it only happens with the first card, and if you move it slowly, instead of releasing the card. I would not want to release the sim like this, but showstopper to me says the sim really won't work/crash. Again, should be addressed, should be top priority.

**Comment by pixelzoom** [comment]
It doesn't happen only with the first card.

**Comment by ariel-phet** [comment]
It seemed once the output carousel has a card in it, the problem goes away? This is what I observed

**Comment by pixelzoom** [comment]
Drag the card back through the carousel and the problem will continue.  As noted in https://github.com/phetsims/function-builder/issues/35#issuecomment-218550795.

**Comment by ariel-phet** [comment]
Updating my iPad currently, will take a look when that is done (wouldn't it be nice if the update fixed it...)

**Comment by phet-steele** [comment]
@ariel-phet it would be nice, because the update fixed this problem on Witten (dev.25 & 28). Let's see if the streak continues with your iPad!

**Comment by jonathanolson** [comment]
I'll plan to wait to hear about testing before looking more into this (I also only have an iPad 3, so I wouldn't be able to reproduce).

**Comment by ariel-phet** [comment]
@phet-steele can you check on Tycho....issue still seems to be appearing on 9.3.2 for me

**Comment by phet-steele** [comment]
@ariel-phet Tycho is fixed, too!

**Comment by jonathanolson** [comment]
@ariel-phet, what testing device would I need to use (on Thursday?) to see if there's anything I can do? This seems more like an "update and it is fixed" type of issue?

**Comment by ariel-phet** [comment]
Not sure...I am going to bring mine in for @phet-steele to take a gander at..I performed the update. I also rebooted, but the issue still seems to be appearing. And I believe I have an identical device (iPad2 iOS 9.3.2)

**Comment by pixelzoom** [comment]
I upgraded my iPad2 to iOS 9.3.2, and I no longer see this problem in 1.0.0-dev.25, or in the more recent 1.0.0-dev.29.

**Comment by ariel-phet** [comment]
I updated, rebooted, cleared cache...still seeing the issue on 1.0.0-dev.30. Very odd. I will bring my iPad on Thursday

**Comment by jonathanolson** [comment]
It's possible that switching something to Canvas may work around this issue. Setting the entire sim to Canvas isn't a great idea, due to the amount opacity is used (current implementation may overflow memory if rootRenderer=canvas is used on iOS).

**Comment by phet-steele** [comment]
I tried @ariel-phet's iPad and indeed it wasn't working. Then when comparing his iPad to Witten and Tycho, the problem returned on all iPads, don't know how.

**Comment by ariel-phet** [comment]
On @pixelzoom suggestion tried on my iPad with ?populateOutput and problem disappeared. Intriguing.

**Comment by phet-steele** [comment]
It was discovered on Thursday that this issue is dependent of whether or not another tab is open. Can't currently remember if another tab breaks it or fixes it.

**Comment by pixelzoom** [comment]
@ariel-phet told me that @jonathanolson has tried several things and is at a loss for what might be causing this. 

@jonathanolson (1) Please indicate what you've tried in this issue. (2) Contact me, I have some suspicions.

**Comment by pixelzoom** [comment]
I was thinking that this issue might be related to function-builder's use of scenery's DAG feature.  Each card has 2 parents, one of which is the "see inside" layer (seeInsideLayer is SceneNode).   I disabled use of the DAG by commenting out SeeInsideLayer.addCardNode, like so:

```js
    addCardNode: function( cardNode ) {
     // this.cardsParent.addChild( cardNode );
    }
```

Unfortunately the problem persisted, so this is likely not related to DAG.

**Comment by jonathanolson** [comment]
I haven't tried any code changes to make the problem go away, planning on doing that after Canvas code changes to Scenery.

If we need a faster (hacky) workaround, I suggested to @ariel-phet that we could try an invisible card in the "output" area on the right (since that seems to prevent this from happening).

It's likely a very specific layering and clipping issue present in Safari, where minor changes to the order of what is rendered could cause it to not occur.

Additionally, since the right button above (and maybe the left) have their stroke clipped, swapping the visual order of the buttons and other things may work around it.

**Comment by pixelzoom** [comment]
> If we need a faster (hacky) workaround, I suggested to @ariel-phet that we could try an invisible card in the "output" area on the right (since that seems to prevent this from happening).

The output carousel currently has an invisible empty "containers" for each card type, which can be seen if you run with `?showContainers`.  And adding an invisible card to each of these containers will not be an encapsulated hack. And it will likely cause multiple problems, since there is code that processes the contents of the containers.  So this hack is a last resort.

**Comment by pixelzoom** [comment]
> Additionally, since the right button above (and maybe the left) have their stroke clipped, swapping the visual order of the buttons and other things may work around it.

The button that is transparent has its stroke clipped, the button that is opaque does not. And this remains true as the button selection changes. Perhaps this is a clue?

**Comment by jonathanolson** [comment]
Potentially, although it seems the main area where the clipping occurs does not have transparency? (SVG is used, so presumably the opacity-related Canvas issues don't apply here).

**Comment by pixelzoom** [comment]
Running the sim with `?populateOutput` puts 1 instance of each card in the output carousel. And in that case, there's no sign of this problem.  So that would seem to increase the probability that putting an invisible card permanently in the output carousel would be an effective (last resort) workaround to this problem.

**Comment by pixelzoom** [comment]
For posterity, here's a screenshot showing the problem on my iPad2.  The green arrow points to one of the rectangular blocks of "damage" that appear as you drag a card through the builder. The red arrow points to similar damage in the unselected scene radio button.  Note that the selected radio button has no such damage to its stroke.

![35](https://cloud.githubusercontent.com/assets/3046552/15763431/387c8718-28e1-11e6-9d9a-6b399ca85058.png)

**Comment by pixelzoom** [comment]
On 5/26/16 in https://github.com/phetsims/function-builder/issues/35#issuecomment-222059080, @jonathanolson said:
> I haven't tried any code changes to make the problem go away, planning on doing that after Canvas code changes to Scenery.

@jonathanolson When do you anticipate that these Canvas changes will be completed?

**Comment by jonathanolson** [comment]
Planning to test this tomorrow in person. @phet-steele, what device would be ideal for testing workarounds for this?

**Comment by phet-steele** [comment]
@jonathanolson Tycho for sure.

**Comment by pixelzoom** [comment]
Regarding the fix, in https://github.com/phetsims/scenery/issues/518#issuecomment-224814416, @jonathanolson said:
>  I haven't done any specific performance tests for this (seemed fine on laptop), but it could somewhat slow Canvas rendering.

Let's make sure that the fix hasn't impacted performance or responsiveness (e.g. https://github.com/phetsims/function-builder/issues/36, https://github.com/phetsims/function-builder/issues/37).

**Comment by jonathanolson** [comment]
The above workaround seems to fix the issue on Tycho. @phet-steele, can you test on other devices where this was happening (and maybe Tycho?)

**Comment by pixelzoom** [comment]
Related Skype chat with @jonathanolson:

[6/9/16, 10:47:22 AM] Jonathan Olson: Pushed workaround for iOS white drag issue
[6/9/16, 10:47:30 AM] Jonathan Olson: Seems to fix it on Tycho without hurting performance
[6/9/16, 10:47:37 AM] Chris Malley: awesome
[6/9/16, 10:48:09 AM] Chris Malley: which repo has the workaround?
[6/9/16, 10:48:13 AM] Jonathan Olson: It turns the PatternsSceneControl to Canvas on iOS. Might trigger "Canvas in background, be careful about repaint"
[6/9/16, 10:48:16 AM] Jonathan Olson: function-builder itself
[6/9/16, 10:48:47 AM] Jonathan Olson: I really don't have enough information to provide a general hack workaround in Scenery
[6/9/16, 10:51:13 AM] Chris Malley: So not a general issue in RadioButtonGroup, which PatternsSceneControl extends?
[6/9/16, 10:51:35 AM] Chris Malley: Just something about where this control happens to sit in the document?
[6/9/16, 10:53:05 AM] Jonathan Olson: Seems potentially that way, yes. Since the bug is (presumably) in mobile Safari, and doesn't cause an exception, I basically can test things and see if "it happens" or "it doesn't happen"
[6/9/16, 10:53:32 AM] Jonathan Olson: It would take a lot of shooting in the dark to identify exactly what the cause is
[6/9/16, 10:53:41 AM] Jonathan Olson: that seems to be triggering Safari to do that
[6/9/16, 10:54:19 AM] Chris Malley: verifying on my iPad2...
[6/9/16, 10:55:55 AM] Chris Malley: Verified.

**Comment by pixelzoom** [comment]
@jonathanolson Since we have a workaround in function-builder and not a fix... Is there any general issue that needs to be created out of this, for future exploration?

**Comment by pixelzoom** [comment]
[6/9/16, 11:00:10 AM] Jonathan Olson: Up to you. If someone runs into a similar iOS bug, we'd want to explore more.
[6/9/16, 11:02:45 AM] Jonathan Olson: Usually, I'd be the one that would notice the similarity (I'd get pinged on something that Scenery-related), and would handle it then

**Comment by pixelzoom** [comment]
@phet-steele I've verified this on my iPad2.  If all goes well with testing on other devices, please close this issue.

**Comment by phet-steele** [comment]
@pixelzoom @jonathanolson fixed on first screen, but not the next two screens.

**Comment by pixelzoom** [comment]
Ugh, good catch @phet-steele, forgot to test on the other screens. And the workaround was added to `SceneControlButtons`, which is used only on the first (Patterns) screen.

**Comment by pixelzoom** [comment]
Since only works for the first screen, I've removed the workaround that was applied in https://github.com/phetsims/function-builder/commit/b9c5b1bf1b17faf059da84e8d40ff063767ebb4f.

**Comment by pixelzoom** [comment]
Workaround attempt #2:
Since the workaround in https://github.com/phetsims/function-builder/commit/b9c5b1bf1b17faf059da84e8d40ff063767ebb4f involved changing the Pattern's screen RadioButtonGroup to `renderer:'canvas'`, I tried putting a similar RadioButtonGroup on the Numbers screen, also with `renderer:'canvas'`. It did not fix the problem.

**Comment by pixelzoom** [comment]
Workaround #3:
Since having a card in the output carousel seems to make the problem go away, I tried turning on "ghost card" images for the output carousels.  This did not fix the problem.

**Comment by pixelzoom** [comment]
Workaround #4:
I noticed that if I dragged a card to the right of the builder, that also seemed to resolve the issue for subsequent cards that I dragged.  So I tried putting a card to the right of the builder, in the `cardDragLayer`, with `pickable:false`.  This did not fix the problem.   

For posterity, here's the code that I added to the end of SceneNode's constructor:

```js
   // Workaround attempt for #35
    {
      var Vector2 = require( 'DOT/Vector2' );
      var inputContainer = inputContainers[ 0 ];
      var outputContainer = outputContainers[ 0 ];
      var card = inputContainer.createCard( inputContainer.value, new Vector2( scene.builder.right + 75, scene.builder.location.y ) );
      var cardNode = inputContainer.createCardNode( card, inputContainer, outputContainer, builderNode, cardsDragLayer, viewProperties.seeInsideProperty );
      cardNode.pickable = false;
      this.addChild( cardNode );
    }
```

**Comment by pixelzoom** [comment]
Workaround #5:
Since having a card in the output carousel (either by dragging one there or using `?populateOutput`) seems to make the problem go away, I tried adding a card to the output carousel.  Adding it using `MovableNode.addNode` would cause a lot of problems, so I tried adding it using `addChild`.  This did not fix the problem.

For posterity, here's the code added to the end of SceneNode:

```js
    // Workaround attempt for #35
    {
      var Vector2 = require( 'DOT/Vector2' );
      var inputContainer = inputContainers[ 0 ];
      var outputContainer = outputContainers[ 0 ];
      var card = inputContainer.createCard( inputContainer.value, new Vector2( 0, 0 ) );
      var cardNode = inputContainer.createCardNode( card, inputContainer, outputContainer, builderNode, cardsDragLayer, viewProperties.seeInsideProperty );
      cardNode.pickable = false;
      outputContainer.addChild( cardNode );
    }
```

**Comment by pixelzoom** [comment]
Workaround #6 (commit immediately above):

Create 1 extra instance of each card, make the extra instances invisible and move them to their appropriate output carousel containers at startup. This *does* fix the problem, and it's encapsulated in SceneNode.  

I'm a little perplexed about why it continues to work OK after Reset All or 'eraser' button, since those actions move the extra cards back to the input carousel. 

This workaround is demonstrated in:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.51/function-builder_en.html

**Comment by pixelzoom** [comment]
Workaround #7 (commit immediately above):

This is a variation of workaround 6.  Instead of creating an extra instance of every card, it create an extra instance of the first card only.  This *does* fix the problem, and will less overall resource requirements than workaround 6.

This workaround is demonstrated in:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.52/function-builder_en.html

**Comment by pixelzoom** [comment]
Ah rats... Workarounds 6 & 7 actually don't work after Reset All or pressing the "eraser" button.  So I'll need to add code that re-applies the workaround after those actions.

**Comment by pixelzoom** [comment]
Workaround 8 (commit immediately above):

Since workarounds 6 & 7 seemed to continue to work after Reset All or erase, I tried simply moving 1 instance of each card to the output carousel (as for the `?populateOutput` query parameter), then calling erasing the output carousel.  This did not work.

Because this did not work, it made me take a close look at workarounds 6 & 7.  And they actually don't work after Reset All or pressing the "eraser" button. So I'll need to add code that re-applies the workaround after those actions.

**Comment by pixelzoom** [comment]
I'm going to go with workaround 7, which I've patched to be re-applied after Reset All and erase.  Here's a dev version that demonstrates the workaround:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.53/function-builder_en.html

@phet-steele Could you please verify the workaround in this dev version? Make sure that it works on all screens, before and after pressing the "Reset All" button, and before and after pressing the "eraser" button.  Thanks.

**Comment by pixelzoom** [comment]
Skype chat with @phet-steele, testing 1.0.0-dev.53:

[6/13/16, 11:15:22 AM] Steele Dalton: naw, this is bad
[6/13/16, 11:15:27 AM] Chris Malley: ?
[6/13/16, 11:16:05 AM] Steele Dalton: start the sim and press the erase button a few times
[6/13/16, 11:16:15 AM] Chris Malley: checking...
[6/13/16, 11:16:22 AM] Steele Dalton: (which is the first thing i did :))
[6/13/16, 11:16:47 AM] Steele Dalton: two times will do it
[6/13/16, 11:17:08 AM] Chris Malley: Ah, I see. Cards disappear from the input container. Hmmm.
[6/13/16, 11:17:40 AM] Steele Dalton: reset does the same
[6/13/16, 11:17:55 AM] Chris Malley: Same with Reset All.
[6/13/16, 11:18:17 AM] Chris Malley: should be able to figure that out. does it look ok otherwise?
[6/13/16, 11:18:34 AM] Chris Malley: i.e., are the graphical artifacts gone?
[6/13/16, 11:19:00 AM] Steele Dalton: also only if you havent actually used the first card does this break, checking the white path stand by
[6/13/16, 11:20:34 AM] Steele Dalton: not fixed
[6/13/16, 11:20:57 AM] Chris Malley: scenario to reproduce?
[6/13/16, 11:21:31 AM] Steele Dalton: on reset
[6/13/16, 11:21:47 AM] Steele Dalton: then drag, happens on the right side of the machine
[6/13/16, 11:22:03 AM] Steele Dalton: scratch that, all sides
[6/13/16, 11:22:08 AM] Chris Malley: so the steps are:
[6/13/16, 11:23:02 AM] Chris Malley: 1. start sim, 2. press reset all, 3. reproduce?
[6/13/16, 11:23:27 AM] Steele Dalton: yup
[6/13/16, 11:23:47 AM] Steele Dalton: even if you have dragged cards prior to resest
[6/13/16, 11:24:22 AM] Steele Dalton: weird, i thought you specifically saw this working after reset?
[6/13/16, 11:24:27 AM] Chris Malley: i did. consistently.
[6/13/16, 11:24:43 AM] Chris Malley: but i see what you're saying.
[6/13/16, 11:26:25 AM] Chris Malley: you can stop testing. let me investigate the obvious Reset All and erase problem, and see if that's causing the workaround to fail.

**Comment by pixelzoom** [comment]
I fixed the issues with Reset All and erase in workaround 7, see commit directly above.  But @phet-steele pointed out that while this extra card is invisible in the output carousel, it's is resulting in an entry in the table, and a point on the graph.  This is what I meant in https://github.com/phetsims/function-builder/issues/35#issuecomment-225626210, when I said "Adding it using MovableNode.addNode would cause a lot of problems".  Putting something in the output carousel causes all kinds of things to happen.

So... I'm going to bail on this workaround, and start looking for something else.

**Comment by pixelzoom** [comment]
And now the detective work begins... Looking through the couple of comments that @jonathanolson made in this issue:

https://github.com/phetsims/function-builder/issues/35#issuecomment-222059080:
> I haven't tried any code changes to make the problem go away, planning on doing that after Canvas code changes to Scenery.

Presumably this meant https://github.com/phetsims/scenery/issues/546, which fixed several Edge issues. That didn't fix this issue, which is undoubtedly why @jonathanolson applied the ineffective workaround in https://github.com/phetsims/function-builder/issues/35#issuecomment-224956542.

> If we need a faster (hacky) workaround, I suggested to @ariel-phet that we could try an invisible card in the "output" area on the right (since that seems to prevent this from happening).

I've now been down that rathole in multiple ways, the most promising of which was workaround 7 in 1.0.0-dev.53.

> It's likely a very specific layering and clipping issue present in Safari, where minor changes to the order of what is rendered could cause it to not occur.
> Additionally, since the right button above (and maybe the left) have their stroke clipped, swapping the visual order of the buttons and other things may work around it.

I'll try to decipher these clues to come up with another workaround approach.

**Comment by pixelzoom** [comment]
@phet-steele Skye:
> so idk if you picked up on it when i asked, but a big clue for #35 is that nothing breaks with two tabs open in safari

Good to know.  But "open a 2nd tab" probably isn't a viable workaround.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> It's likely a very specific layering and clipping issue present in Safari, where minor changes to the order of what is rendered could cause it to not occur.

I've gone through the layering and clipping, and haven't identified anything that can be changed. The layering order and clipping is very specific to achieving the desired effects/features.

**Comment by pixelzoom** [comment]
Here's the layering in SceneNode. I've indicated the layers that involve 1 or more clipAreas.

```js
    options.children = [
      controlsLayer,
      inputCarousel, // 1 clipArea
      inputPageControl,
      outputCarousel, // 1 clipArea 
      outputPageControl,
      functionCarousel, // 1 clipArea 
      functionPageControl,
      drawersLayer, // table: 2 clipAreas, graph: 1 clipArea, equations: 1 clipArea 
      builderLeftEndNode, 
      builderRightEndNode,
      cardsDragLayer,
      builderNode, // 1 clipArea
      seeInsideLayer, // 1 clipArea
      functionsDragLayer
    ];
```

**Comment by pixelzoom** [comment]
Workaround-9:  
Tried grouping layers that use clipArea, as shown below. Did not fix.

```js
    options.children = [
      controlsLayer,
      inputPageControl,
      outputPageControl,
      functionPageControl,
      builderLeftEndNode,
      builderRightEndNode,
      inputCarousel, // 1 clipArea
      outputCarousel, // 1 clipArea
      functionCarousel, // 1 clipArea
      drawersLayer, // table: 2 clipAreas, graph: 1 clipArea, equations: 1 clipArea
      cardsDragLayer,
      builderNode, // 1 clipArea
      seeInsideLayer, // 1 clipArea
      functionsDragLayer
    ];
```

**Comment by pixelzoom** [comment]
Workaround-9b:

Another layering variation (add layers with clipAreas first where possible) as shown below. This *does* appear to fix the problem. 

```js
    options.children = [
      inputCarousel, // 1 clipArea
      outputCarousel, // 1 clipArea
      functionCarousel, // 1 clipArea
      drawersLayer, // table: 2 clipAreas, graph: 1 clipArea, equations: 1 clipArea
      builderLeftEndNode,
      builderRightEndNode,
      cardsDragLayer,
      builderNode, // 1 clipArea
      seeInsideLayer, // 1 clipArea
      controlsLayer,
      inputPageControl,
      outputPageControl,
      functionPageControl,
      functionsDragLayer
    ];
```

Demonstrated in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.55/function-builder_en.html

**Comment by pixelzoom** [comment]
@phet-steele Could you please test drive 1.0.0-dev.55?

**Comment by pixelzoom** [comment]
@phet-steele reported that the problem was still occurring.  After clearing web data and restarting Safari, I am also seeing the problem again.  So apparently workaround-9b didn't change anything.

**Comment by pixelzoom** [comment]
OK... So no luck with the layering order workaround.  @jonathanolson's first workaround involved setting `renderer:'canvas'` for PatternsSceneControl.  So I'll try setting `renderer:'canvas'` for miscellaneous UI components in hope that one of them will matter.

**Comment by pixelzoom** [comment]
Workaround-10a:

For `platform.mobileSafari`, I applied `{ renderer: 'canvas'}` to `controlsLayer` (misc UI controls) in SceneNode.  After clearing web data and restarting Safari several times, this appears to fix the problem for all screens. (But given the history of this bug, it will probably reanimate immediately after @phet-steele starts testing :) 

@phet-steele please try to break this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.56/function-builder_en.html

**Comment by ariel-phet** [comment]
I tried 1.0.0-dev.56 on Loeblein (Ipad2 that had previously exhibited the issue), and I cannot reproduce.

Tried both before and after clearing website data, and all looks good. Although not an exhaustive "full-Steele" test, it appears promising.

**Comment by pixelzoom** [comment]
The fix is actively only on mobile Safari, and it involves using 'renderer: 'canvas'  for the controls layer - which includes the Reset All button, eraser button, and page controls for the carousels.  The only negative consequence might be in rendering quality for those controls, but they look fine to me.

Closing.  (Whew.)

**Comment by pixelzoom** [comment]
Skype chat from a last week with @jonathanolson:

> [6/9/16, 10:57:03 AM] Chris Malley: Any general issue that needs to be created out of this, for future exploration?
[6/9/16, 11:00:10 AM] Jonathan Olson: Up to you. If someone runs into a similar iOS bug, we'd want to explore more.
[6/9/16, 11:02:45 AM] Jonathan Olson: Usually, I'd be the one that would notice the similarity (I'd get pinged on something that Scenery-related), and would handle it then
[6/9/16, 11:17:18 AM] Chris Malley: OK, I won't bother.

So even though we didn't really fix this, I'm not going to create any general scenery issue.   I did create https://github.com/phetsims/function-builder/issues/69 to revisit removing the workaround in the future.

**Comment by pixelzoom** [comment]
And thank you @phet-steele for testing this multiple times as I investigated various workarounds.

**Comment by pixelzoom** [comment]
After making a bunch of changes to SceneNode for the new Mystery screen, I retested and verified that this issue has not returned.  Here's a dev version with the changes:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.57/function-builder_en.html
